### ISSUE TITLE
Not working as intended

### ISSUE THREAD

**Issue by EndlessFractal** [Vinnl/feeds#3]
Hello!

Many thanks for making such a project.

I followed all the steps in the tutorial but couldn't make it work. 
I've checked other people's forks and none of their pages work either.

Could you help?

Many thanks!

**Comment by Barabazs** [comment]
Hi @Vinnl There is an issue with the "Deploy to Github Pages" part of the workflow.
The "public" folder doesn't exist. 
![image](https://user-images.githubusercontent.com/31799121/131313322-1ef844e4-1449-4cf1-be51-4873ccf64c2f.png)

**Comment by Vinnl** [comment]
Hi @NotoriusNeo, unfortunately sometimes fetching fails, but as you can see if you take another look at your feed, later attempts did work.

Unfortunately GitHub Actions doesn't make it easy to automatically retry on such failures. However, I've added a workaround in the latest version of `.github/workflows/pages.yml`, so if you [copy those lines](https://github.com/Vinnl/feeds/blob/ffda04daf82005e482ddd8e8f3aa386fba4b3e90/.github/workflows/pages.yml#L22-L24) or merge in the latest version, you should hopefully get fewer failures.

@Barabazs The failure was actually already in the `feed-me-up-scotty` part (which should generate that `public` folder), but it erroneously did not fail the job. That should be fixed with the release I pushed just now.

**Comment by EndlessFractal** [comment]
Hello! Thanks for your feedback!

The script is now acting oddly.  
> page.goto: Navigating frame was detached!

Could this be just a coincidence and an issue with the website that I'm generating a feed from?

Appreciated!

**Comment by Vinnl** [comment]
@NotoriusNeo Weird, using the same config it works for me - maybe a temporary glitch with either the website or GitHub Actions? You could try retrying it or just waiting to see if it resolves itself, or possibly try the [experimental options](https://feed-me-up-scotty.vincenttunru.com/docs/setup) `waitUntil` and/or `waitForSelector` to see if those can help?

**Comment by EndlessFractal** [comment]
I think it's working correctly now! I believe it was an issue with the website.

Many thanks!

**Comment by Vinnl** [comment]
Great, thanks for reporting back!

**Comment by Barabazs** [comment]
Thank you @Vinnl !
